---
sidebar: sidebar 
permalink: install-setup/install-setup-requirements.html 
keywords: aide, ai, data engine, ai data engine, dcn, data compute node, afx, afx 1k, install, setup, requirements, cautions, 
summary: 'Examinez l"équipement nécessaire et les précautions de levage pour vos nœuds de calcul de données pour AI Data Engine.' 
---
= Configuration requise pour les nœuds de calcul de données pour AI Data Engine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Examinez l'équipement nécessaire et les précautions de levage pour vos nœuds de calcul de données pour AI Data Engine.



== Prérequis

Avant d'installer les nœuds de calcul de données pour AIDE, assurez-vous de disposer des éléments suivants :

* Un système de stockage AFX 1K.
+

NOTE: Pour plus d'informations sur l'installation du système de stockage AFX 1K, reportez-vous au link:https://docs.netapp.com/us-en/ontap-afx/install-setup/install-setup-workflow.html["Installez votre système de stockage AFX 1K"^].





== Matériel nécessaire à l'installation

Pour installer les nœuds de calcul de données pour AIDE, vous avez besoin des équipements et outils suivants.

* Accès à un navigateur web pour configurer vos nœuds de calcul de données
* Bracelet antistatique (ESD)
* Lampe de poche
* Ordinateur portable ou console avec une connexion USB/série
* Tournevis Phillips n° 2




== Précautions de levage

Les nœuds de calcul de données sont lourds. Faites preuve de prudence lors du levage et du déplacement de ces éléments.



=== Poids des nœuds de calcul de données

Prenez les précautions nécessaires lors du déplacement ou du levage de votre nœud de calcul de données.

Un nœud de calcul de données peut peser jusqu'à 46,3 lbs (21 kg). Pour soulever le nœud de calcul de données, utilisez deux personnes ou un élévateur hydraulique.

image::../media/drw_compute_node_lifting_weight_ieops-2743.svg[Poids de levage du nœud de calcul de données]

.Informations connexes
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informations de sécurité et avis réglementaires"^]


.Et ensuite ?
Après avoir examiné les exigences matérielles, vous link:prepare-hardware.html["Préparez-vous à installer vos nœuds de calcul de données"].
