---
sidebar: sidebar 
permalink: administer/dcn-add-node.html 
keywords: aide, ai data engine, data compute node, dcn, add dcn, expand dcn cluster 
summary: 'Vous pouvez ajouter des nœuds de calcul de données lors de la création d"un nouveau cluster AI Data Engine (AIDE) ou de l"extension d"un cluster existant.' 
---
= Ajoutez des nœuds de calcul de données à votre cluster AI Data Engine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter des nœuds de calcul de données lors de la création d'un nouveau cluster AI Data Engine (AIDE) ou de l'extension d'un cluster existant. Le workflow consiste à découvrir et à configurer les nœuds à l'aide de ONTAP System Manager.



== Préparez-vous à ajouter des nœuds

Tenez compte des points suivants lors de l'ajout de nœuds de calcul de données.

.Nombre minimal de nœuds de calcul de données
Exactement trois nœuds de calcul de données disponibles sont requis pour un nouveau cluster AIDE.

.Installation et adressabilité du matériel
Assurez-vous que les conditions préalables suivantes sont remplies :

* Le nouveau matériel de calcul de données est installé en rack, mis sous tension et câblé aux commutateurs du cluster.
* Vous disposez d'une plage d'adresses IP pour les nœuds de calcul de données vers le sous-réseau dorsal ONTAP.
* Le ONTAP cluster a été initialisé et est accessible depuis l'interface logique de gestion du cluster (LIF).


.Identifiants System Manager
Vous devez disposer des privilèges d'administrateur de stockage pour effectuer des tâches de création ou d'extension de cluster AIDE.

.Compatibilité logicielle
Veuillez consulter la documentation suivante pour confirmer que vos versions matérielles et logicielles de calcul de données sont compatibles avec votre cluster ONTAP :

* link:../administer/upgrades-aide-summary.html["Le logiciel AIDE est compatible avec la version ONTAP"].


Lors de l'ajout de nœuds, System Manager vérifiera que les nouveaux nœuds exécutent une version logicielle compatible avec :

* La version effective du cluster ONTAP si c'est le premier nœud de calcul de données ajouté.
* La version existante du cluster de calcul de données si des nœuds de calcul de données sont déjà présents.


Si un nœud est incompatible :

* Une erreur s'affiche à côté du nœud de calcul de données concerné dans la boîte de dialogue *Ajouter*.
* Vous devez d'abord mettre à jour le logiciel du nœud de calcul de données (ou ONTAP, selon le cas) vers une version compatible.




== Ajouter les nœuds de calcul de données

Ajoutez des nœuds de calcul de données lors de la création d'un nouveau cluster AIDE ou de l'extension d'un cluster existant.

.Étapes
. Dans System Manager, sélectionnez *Dashboard* dans le volet de navigation, puis la carte *Health*.
. Vérifiez qu'il y a des nœuds à ajouter et sélectionnez *Afficher les détails* pour afficher la liste.
+
La liste contient les nœuds découverts qui ne font pas encore partie du cluster AIDE.

. Vous pouvez également sélectionner *Cluster* et *Overview* et l'onglet *Data compute* pour afficher la liste.
. En bas de la page de calcul des données, sélectionnez *Ajouter* au-dessus de la liste des nœuds.
. Dans la boîte de dialogue *Ajouter des nœuds*, sélectionnez les nœuds de calcul de données que vous souhaitez ajouter.
. Si vous ajoutez des nœuds pour la première fois et qu'aucun sous-réseau backend n'existe, sélectionnez *Add subnet* et indiquez :
+
** Nom du sous-réseau (à usage interne)
** Adresse et masque du sous-réseau
** Plage d'adresses IP pour les nœuds de calcul de données et les nœuds ONTAP sur le réseau dorsal
+
System Manager vérifie que la plage comprend suffisamment d'adresses IP libres pour tous les nœuds de calcul de données ajoutés, tous les nœuds ONTAP du cluster, et les adresses IP flottantes supplémentaires au niveau du cluster utilisées pour la communication entre les nœuds de calcul de données et ONTAP.



. Procédez comme suit, que vous ayez ajouté le sous-réseau backend ou qu'il existe déjà :
+
.. Examinez les adresses IP disponibles.
.. Si nécessaire, sélectionnez *Modifier le sous-réseau* et étendez la plage IP.
+
*** Vous pouvez uniquement étendre la plage. La réduction ou la modification du sous-réseau n'est pas prise en charge.
*** Modifier le sous-réseau ou la plage d'adresses IP peut nécessiter la recréation du cluster Kubernetes sous-jacent sur les nœuds de calcul de données et peut prendre plusieurs minutes.




. Vous pouvez éventuellement configurer l'interface du service Data Engine en fournissant :
+
** Adresse IP du service
** Masque de réseau
** Passerelle (si nécessaire pour votre environnement)
+
L'adresse IP unique sera répartie entre les nœuds de calcul de données et utilisée comme adresse frontale pour AI Data Engine Console et les API associées.



. Vérifiez les nœuds sélectionnés, le sous-réseau dorsal et les paramètres de l'interface du service Data Engine.
. Sélectionnez *Ajouter* et attendez la fin de l'opération. System Manager effectuera les actions suivantes :
+
** Ajouter les nœuds sélectionnés au cluster de calcul de données
** Provisionnez le réseau dorsal et joignez les nœuds au cluster de calcul de données basé sur Kubernetes
** Mise à jour des métadonnées internes pour la découverte des nœuds de calcul de données


. Une fois terminé, sélectionnez *Cluster* et *Overview* et confirmez :
+
** Sous *Calcul de données*, les nouveaux nœuds de calcul de données apparaissent en ligne en tant que partie du cluster
** Tous les nœuds sont *Healthy*
** La version d'AIDE s'affiche correctement pour chaque nœud
** Vérifiez que la carte *Santé* du tableau de bord affiche le nombre de nœuds mis à jour


. (Facultatif) Une fois que tous les nœuds ont rejoint le cluster, vérifiez que tous les services démarrent correctement.
+
.. Vérifier l'état du pod Kubernetes :
+
[source, bash]
----
kubectl get pods -n aide-system
----
.. Vérifiez que tous les pods affichent le statut *En cours d'exécution* ou *Terminé*.



